# Generated by Django 3.0.3 on 2020-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='base',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado'),
        ),
    ]
