# Generated by Django 3.0.3 on 2020-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200218_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
    ]
