# Generated by Django 3.0.3 on 2020-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200218_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='bio',
            field=models.CharField(default=1, max_length=300, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
